//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/similar/MoreLikeThisQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThisQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchSimilarMoreLikeThisQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThisQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThisQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchSimilarMoreLikeThisQuery

#if !defined (OrgApacheLuceneSearchSimilarMoreLikeThisQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThisQuery || defined(INCLUDE_OrgApacheLuceneSearchSimilarMoreLikeThisQuery))
#define OrgApacheLuceneSearchSimilarMoreLikeThisQuery_

#define RESTRICT_OrgApacheLuceneSearchQuery 1
#define INCLUDE_OrgApacheLuceneSearchQuery 1
#include "org/apache/lucene/search/Query.h"

@class IOSObjectArray;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneIndexIndexReader;
@protocol JavaUtilSet;

@interface OrgApacheLuceneSearchSimilarMoreLikeThisQuery : OrgApacheLuceneSearchQuery

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)likeText
               withNSStringArray:(IOSObjectArray *)moreLikeFields
withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (instancetype)initWithNSString:(NSString *)likeText
               withNSStringArray:(IOSObjectArray *)moreLikeFields
withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer
                    withNSString:(NSString *)fieldName;

- (OrgApacheLuceneAnalysisAnalyzer *)getAnalyzer;

- (NSString *)getLikeText;

- (jint)getMaxQueryTerms;

- (jint)getMinDocFreq;

- (jint)getMinTermFrequency;

- (IOSObjectArray *)getMoreLikeFields;

- (jfloat)getPercentTermsToMatch;

- (id<JavaUtilSet>)getStopWords;

- (OrgApacheLuceneSearchQuery *)rewriteWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (void)setAnalyzerWithOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (void)setLikeTextWithNSString:(NSString *)likeText;

- (void)setMaxQueryTermsWithInt:(jint)maxQueryTerms;

- (void)setMinDocFreqWithInt:(jint)minDocFreq;

- (void)setMinTermFrequencyWithInt:(jint)minTermFrequency;

- (void)setMoreLikeFieldsWithNSStringArray:(IOSObjectArray *)moreLikeFields;

- (void)setPercentTermsToMatchWithFloat:(jfloat)percentTermsToMatch;

- (void)setStopWordsWithJavaUtilSet:(id<JavaUtilSet>)stopWords;

- (NSString *)toStringWithNSString:(NSString *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchSimilarMoreLikeThisQuery)

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchSimilarMoreLikeThisQuery *self, NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer);

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThisQuery *new_OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_(NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThisQuery *create_OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_(NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer);

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_withNSString_(OrgApacheLuceneSearchSimilarMoreLikeThisQuery *self, NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer, NSString *fieldName);

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThisQuery *new_OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_withNSString_(NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer, NSString *fieldName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThisQuery *create_OrgApacheLuceneSearchSimilarMoreLikeThisQuery_initWithNSString_withNSStringArray_withOrgApacheLuceneAnalysisAnalyzer_withNSString_(NSString *likeText, IOSObjectArray *moreLikeFields, OrgApacheLuceneAnalysisAnalyzer *analyzer, NSString *fieldName);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchSimilarMoreLikeThisQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThisQuery")
