//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/regex/RegexQueryCapable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQueryCapable")
#ifdef RESTRICT_OrgApacheLuceneSearchRegexRegexQueryCapable
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQueryCapable 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQueryCapable 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchRegexRegexQueryCapable

#if !defined (OrgApacheLuceneSearchRegexRegexQueryCapable_) && (INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQueryCapable || defined(INCLUDE_OrgApacheLuceneSearchRegexRegexQueryCapable))
#define OrgApacheLuceneSearchRegexRegexQueryCapable_

@protocol OrgApacheLuceneSearchRegexRegexCapabilities;

@protocol OrgApacheLuceneSearchRegexRegexQueryCapable < JavaObject >

- (void)setRegexImplementationWithOrgApacheLuceneSearchRegexRegexCapabilities:(id<OrgApacheLuceneSearchRegexRegexCapabilities>)impl;

- (id<OrgApacheLuceneSearchRegexRegexCapabilities>)getRegexImplementation;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchRegexRegexQueryCapable)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchRegexRegexQueryCapable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQueryCapable")
