//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/regex/RegexQueryCapable.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/regex/RegexQueryCapable.h"

@interface OrgApacheLuceneSearchRegexRegexQueryCapable : NSObject

@end

@implementation OrgApacheLuceneSearchRegexRegexQueryCapable

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchRegexRegexCapabilities;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(setRegexImplementationWithOrgApacheLuceneSearchRegexRegexCapabilities:);
  methods[1].selector = @selector(getRegexImplementation);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "setRegexImplementation", "LOrgApacheLuceneSearchRegexRegexCapabilities;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchRegexRegexQueryCapable = { "RegexQueryCapable", "org.apache.lucene.search.regex", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchRegexRegexQueryCapable;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchRegexRegexQueryCapable)
