//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/FieldFragList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList")
#ifdef RESTRICT_OrgApacheLuceneSearchVectorhighlightFieldFragList
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchVectorhighlightFieldFragList

#if !defined (OrgApacheLuceneSearchVectorhighlightFieldFragList_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightFieldFragList))
#define OrgApacheLuceneSearchVectorhighlightFieldFragList_

@protocol JavaUtilList;

@interface OrgApacheLuceneSearchVectorhighlightFieldFragList : NSObject

#pragma mark Public

- (instancetype)initWithInt:(jint)fragCharSize;

- (void)addWithInt:(jint)startOffset
           withInt:(jint)endOffset
  withJavaUtilList:(id<JavaUtilList>)phraseInfoList;

- (id<JavaUtilList>)getFragInfos;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightFieldFragList)

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightFieldFragList_initWithInt_(OrgApacheLuceneSearchVectorhighlightFieldFragList *self, jint fragCharSize);

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList *new_OrgApacheLuceneSearchVectorhighlightFieldFragList_initWithInt_(jint fragCharSize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList *create_OrgApacheLuceneSearchVectorhighlightFieldFragList_initWithInt_(jint fragCharSize);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightFieldFragList)

#endif

#if !defined (OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo))
#define OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_

@protocol JavaUtilList;

@interface OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo : NSObject {
 @public
  id<JavaUtilList> subInfos_;
  jfloat totalBoost_;
  jint startOffset_;
  jint endOffset_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)startOffset
                    withInt:(jint)endOffset
           withJavaUtilList:(id<JavaUtilList>)phraseInfoList;

- (jint)getEndOffset;

- (jint)getStartOffset;

- (id<JavaUtilList>)getSubInfos;

- (jfloat)getTotalBoost;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo, subInfos_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_initWithInt_withInt_withJavaUtilList_(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo *self, jint startOffset, jint endOffset, id<JavaUtilList> phraseInfoList);

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo *new_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_initWithInt_withInt_withJavaUtilList_(jint startOffset, jint endOffset, id<JavaUtilList> phraseInfoList) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo *create_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_initWithInt_withInt_withJavaUtilList_(jint startOffset, jint endOffset, id<JavaUtilList> phraseInfoList);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo)

#endif

#if !defined (OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo))
#define OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo_

@protocol JavaUtilList;

@interface OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo : NSObject {
 @public
  NSString *text_;
  id<JavaUtilList> termsOffsets_;
  jint seqnum_;
}

#pragma mark Public

- (jint)getSeqnum;

- (id<JavaUtilList>)getTermsOffsets;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)text
                withJavaUtilList:(id<JavaUtilList>)termsOffsets
                         withInt:(jint)seqnum;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo, text_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo, termsOffsets_, id<JavaUtilList>)

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo_initWithNSString_withJavaUtilList_withInt_(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo *self, NSString *text, id<JavaUtilList> termsOffsets, jint seqnum);

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo *new_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo_initWithNSString_withJavaUtilList_withInt_(NSString *text, id<JavaUtilList> termsOffsets, jint seqnum) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo *create_OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo_initWithNSString_withJavaUtilList_withInt_(NSString *text, id<JavaUtilList> termsOffsets, jint seqnum);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo_SubInfo)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightFieldFragList")
