//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/SingleFragListBuilder.java
//

#include "J2ObjC_source.h"
#include "java/lang/Integer.h"
#include "java/util/ArrayList.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"
#include "org/apache/lucene/search/vectorhighlight/FieldFragList.h"
#include "org/apache/lucene/search/vectorhighlight/FieldPhraseList.h"
#include "org/apache/lucene/search/vectorhighlight/SingleFragListBuilder.h"

@implementation OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (OrgApacheLuceneSearchVectorhighlightFieldFragList *)createFieldFragListWithOrgApacheLuceneSearchVectorhighlightFieldPhraseList:(OrgApacheLuceneSearchVectorhighlightFieldPhraseList *)fieldPhraseList
                                                                                                                          withInt:(jint)fragCharSize {
  OrgApacheLuceneSearchVectorhighlightFieldFragList *ffl = new_OrgApacheLuceneSearchVectorhighlightFieldFragList_initWithInt_(fragCharSize);
  id<JavaUtilList> wpil = new_JavaUtilArrayList_init();
  id<JavaUtilIterator> ite = [((JavaUtilLinkedList *) nil_chk(((OrgApacheLuceneSearchVectorhighlightFieldPhraseList *) nil_chk(fieldPhraseList))->phraseList_)) iterator];
  OrgApacheLuceneSearchVectorhighlightFieldPhraseList_WeightedPhraseInfo *phraseInfo = nil;
  while (true) {
    if (![((id<JavaUtilIterator>) nil_chk(ite)) hasNext]) break;
    phraseInfo = [ite next];
    if (phraseInfo == nil) break;
    [wpil addWithId:phraseInfo];
  }
  if ([wpil size] > 0) [ffl addWithInt:0 withInt:JavaLangInteger_MAX_VALUE withJavaUtilList:wpil];
  return ffl;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchVectorhighlightFieldFragList;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(createFieldFragListWithOrgApacheLuceneSearchVectorhighlightFieldPhraseList:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "createFieldFragList", "LOrgApacheLuceneSearchVectorhighlightFieldPhraseList;I" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder = { "SingleFragListBuilder", "org.apache.lucene.search.vectorhighlight", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder;
}

@end

void OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder_init(OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder *self) {
  NSObject_init(self);
}

OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder *new_OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder, init)
}

OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder *create_OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchVectorhighlightSingleFragListBuilder)
