//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/similar/MoreLikeThis.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThis")
#ifdef RESTRICT_OrgApacheLuceneSearchSimilarMoreLikeThis
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThis 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThis 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchSimilarMoreLikeThis

#if !defined (OrgApacheLuceneSearchSimilarMoreLikeThis_) && (INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThis || defined(INCLUDE_OrgApacheLuceneSearchSimilarMoreLikeThis))
#define OrgApacheLuceneSearchSimilarMoreLikeThis_

@class IOSObjectArray;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoReader;
@class JavaNetURL;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchQuery;
@class OrgApacheLuceneSearchSimilarity;
@class OrgApacheLuceneUtilPriorityQueue;
@protocol JavaUtilSet;

@interface OrgApacheLuceneSearchSimilarMoreLikeThis : NSObject

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)ir;

- (instancetype)initWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)ir
                    withOrgApacheLuceneSearchSimilarity:(OrgApacheLuceneSearchSimilarity *)sim;

- (NSString *)describeParams;

- (OrgApacheLuceneAnalysisAnalyzer *)getAnalyzer;

- (jfloat)getBoostFactor;

- (IOSObjectArray *)getFieldNames;

- (jint)getMaxDocFreq;

- (jint)getMaxNumTokensParsed;

- (jint)getMaxQueryTerms;

- (jint)getMaxWordLen;

- (jint)getMinDocFreq;

- (jint)getMinTermFreq;

- (jint)getMinWordLen;

- (OrgApacheLuceneSearchSimilarity *)getSimilarity;

- (id<JavaUtilSet>)getStopWords;

- (jboolean)isBoost;

- (OrgApacheLuceneSearchQuery *)likeWithJavaIoFile:(JavaIoFile *)f;

- (OrgApacheLuceneSearchQuery *)likeWithJavaIoInputStream:(JavaIoInputStream *)is;

- (OrgApacheLuceneSearchQuery *)likeWithInt:(jint)docNum;

- (OrgApacheLuceneSearchQuery *)likeWithJavaIoReader:(JavaIoReader *)r;

- (OrgApacheLuceneSearchQuery *)likeWithJavaIoReader:(JavaIoReader *)r
                                        withNSString:(NSString *)fieldName;

- (OrgApacheLuceneSearchQuery *)likeWithJavaNetURL:(JavaNetURL *)u;

- (IOSObjectArray *)retrieveInterestingTermsWithInt:(jint)docNum;

- (IOSObjectArray *)retrieveInterestingTermsWithJavaIoReader:(JavaIoReader *)r;

- (IOSObjectArray *)retrieveInterestingTermsWithJavaIoReader:(JavaIoReader *)r
                                                withNSString:(NSString *)fieldName;

- (OrgApacheLuceneUtilPriorityQueue *)retrieveTermsWithInt:(jint)docNum;

- (OrgApacheLuceneUtilPriorityQueue *)retrieveTermsWithJavaIoReader:(JavaIoReader *)r;

- (OrgApacheLuceneUtilPriorityQueue *)retrieveTermsWithJavaIoReader:(JavaIoReader *)r
                                                       withNSString:(NSString *)fieldName;

- (void)setAnalyzerWithOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (void)setBoostWithBoolean:(jboolean)boost;

- (void)setBoostFactorWithFloat:(jfloat)boostFactor;

- (void)setFieldNamesWithNSStringArray:(IOSObjectArray *)fieldNames;

- (void)setMaxDocFreqWithInt:(jint)maxFreq;

- (void)setMaxDocFreqPctWithInt:(jint)maxPercentage;

- (void)setMaxNumTokensParsedWithInt:(jint)i;

- (void)setMaxQueryTermsWithInt:(jint)maxQueryTerms;

- (void)setMaxWordLenWithInt:(jint)maxWordLen;

- (void)setMinDocFreqWithInt:(jint)minDocFreq;

- (void)setMinTermFreqWithInt:(jint)minTermFreq;

- (void)setMinWordLenWithInt:(jint)minWordLen;

- (void)setSimilarityWithOrgApacheLuceneSearchSimilarity:(OrgApacheLuceneSearchSimilarity *)similarity;

- (void)setStopWordsWithJavaUtilSet:(id<JavaUtilSet>)stopWords;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneSearchSimilarMoreLikeThis)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MAX_NUM_TOKENS_PARSED();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MAX_NUM_TOKENS_PARSED 5000
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MAX_NUM_TOKENS_PARSED, jint)

inline OrgApacheLuceneAnalysisAnalyzer *OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_ANALYZER();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgApacheLuceneAnalysisAnalyzer *OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_ANALYZER;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_ANALYZER, OrgApacheLuceneAnalysisAnalyzer *)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MIN_TERM_FREQ();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MIN_TERM_FREQ 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MIN_TERM_FREQ, jint)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MIN_DOC_FREQ();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MIN_DOC_FREQ 5
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MIN_DOC_FREQ, jint)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MAX_DOC_FREQ();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MAX_DOC_FREQ 2147483647
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MAX_DOC_FREQ, jint)

inline jboolean OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_BOOST();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_BOOST false
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_BOOST, jboolean)

inline IOSObjectArray *OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_FIELD_NAMES();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_FIELD_NAMES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_FIELD_NAMES, IOSObjectArray *)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MIN_WORD_LENGTH();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MIN_WORD_LENGTH 0
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MIN_WORD_LENGTH, jint)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MAX_WORD_LENGTH();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MAX_WORD_LENGTH 0
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MAX_WORD_LENGTH, jint)

inline id<JavaUtilSet> OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_STOP_WORDS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<JavaUtilSet> OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_STOP_WORDS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_STOP_WORDS, id<JavaUtilSet>)

inline jint OrgApacheLuceneSearchSimilarMoreLikeThis_get_DEFAULT_MAX_QUERY_TERMS();
#define OrgApacheLuceneSearchSimilarMoreLikeThis_DEFAULT_MAX_QUERY_TERMS 25
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchSimilarMoreLikeThis, DEFAULT_MAX_QUERY_TERMS, jint)

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_(OrgApacheLuceneSearchSimilarMoreLikeThis *self, OrgApacheLuceneIndexIndexReader *ir);

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThis *new_OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_(OrgApacheLuceneIndexIndexReader *ir) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThis *create_OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_(OrgApacheLuceneIndexIndexReader *ir);

FOUNDATION_EXPORT void OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneSearchSimilarity_(OrgApacheLuceneSearchSimilarMoreLikeThis *self, OrgApacheLuceneIndexIndexReader *ir, OrgApacheLuceneSearchSimilarity *sim);

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThis *new_OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneSearchSimilarity_(OrgApacheLuceneIndexIndexReader *ir, OrgApacheLuceneSearchSimilarity *sim) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarMoreLikeThis *create_OrgApacheLuceneSearchSimilarMoreLikeThis_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneSearchSimilarity_(OrgApacheLuceneIndexIndexReader *ir, OrgApacheLuceneSearchSimilarity *sim);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchSimilarMoreLikeThis)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchSimilarMoreLikeThis")
