//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/regexp/StreamCharacterIterator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheRegexpStreamCharacterIterator")
#ifdef RESTRICT_OrgApacheRegexpStreamCharacterIterator
#define INCLUDE_ALL_OrgApacheRegexpStreamCharacterIterator 0
#else
#define INCLUDE_ALL_OrgApacheRegexpStreamCharacterIterator 1
#endif
#undef RESTRICT_OrgApacheRegexpStreamCharacterIterator

#if !defined (OrgApacheRegexpStreamCharacterIterator_) && (INCLUDE_ALL_OrgApacheRegexpStreamCharacterIterator || defined(INCLUDE_OrgApacheRegexpStreamCharacterIterator))
#define OrgApacheRegexpStreamCharacterIterator_

#define RESTRICT_OrgApacheRegexpCharacterIterator 1
#define INCLUDE_OrgApacheRegexpCharacterIterator 1
#include "org/apache/regexp/CharacterIterator.h"

@class JavaIoInputStream;

@interface OrgApacheRegexpStreamCharacterIterator : NSObject < OrgApacheRegexpCharacterIterator >

#pragma mark Public

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)is;

- (jchar)charAtWithInt:(jint)pos;

- (jboolean)isEndWithInt:(jint)pos;

- (NSString *)substringWithInt:(jint)beginIndex;

- (NSString *)substringWithInt:(jint)beginIndex
                       withInt:(jint)endIndex;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheRegexpStreamCharacterIterator)

FOUNDATION_EXPORT void OrgApacheRegexpStreamCharacterIterator_initWithJavaIoInputStream_(OrgApacheRegexpStreamCharacterIterator *self, JavaIoInputStream *is);

FOUNDATION_EXPORT OrgApacheRegexpStreamCharacterIterator *new_OrgApacheRegexpStreamCharacterIterator_initWithJavaIoInputStream_(JavaIoInputStream *is) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheRegexpStreamCharacterIterator *create_OrgApacheRegexpStreamCharacterIterator_initWithJavaIoInputStream_(JavaIoInputStream *is);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheRegexpStreamCharacterIterator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheRegexpStreamCharacterIterator")
