//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/GradientFormatter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightGradientFormatter")
#ifdef RESTRICT_OrgApacheLuceneSearchHighlightGradientFormatter
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightGradientFormatter 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightGradientFormatter 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchHighlightGradientFormatter

#if !defined (OrgApacheLuceneSearchHighlightGradientFormatter_) && (INCLUDE_ALL_OrgApacheLuceneSearchHighlightGradientFormatter || defined(INCLUDE_OrgApacheLuceneSearchHighlightGradientFormatter))
#define OrgApacheLuceneSearchHighlightGradientFormatter_

#define RESTRICT_OrgApacheLuceneSearchHighlightFormatter 1
#define INCLUDE_OrgApacheLuceneSearchHighlightFormatter 1
#include "org/apache/lucene/search/highlight/Formatter.h"

@class OrgApacheLuceneSearchHighlightTokenGroup;

@interface OrgApacheLuceneSearchHighlightGradientFormatter : NSObject < OrgApacheLuceneSearchHighlightFormatter > {
 @public
  jint fgRMin_;
  jint fgGMin_;
  jint fgBMin_;
  jint fgRMax_;
  jint fgGMax_;
  jint fgBMax_;
  jboolean highlightForeground_;
  jint bgRMin_;
  jint bgGMin_;
  jint bgBMin_;
  jint bgRMax_;
  jint bgGMax_;
  jint bgBMax_;
  jboolean highlightBackground_;
}

#pragma mark Public

- (instancetype)initWithFloat:(jfloat)maxScore
                 withNSString:(NSString *)minForegroundColor
                 withNSString:(NSString *)maxForegroundColor
                 withNSString:(NSString *)minBackgroundColor
                 withNSString:(NSString *)maxBackgroundColor;

+ (jint)hexToIntWithNSString:(NSString *)hex;

- (NSString *)highlightTermWithNSString:(NSString *)originalText
withOrgApacheLuceneSearchHighlightTokenGroup:(OrgApacheLuceneSearchHighlightTokenGroup *)tokenGroup;

#pragma mark Protected

- (NSString *)getBackgroundColorStringWithFloat:(jfloat)score;

- (NSString *)getForegroundColorStringWithFloat:(jfloat)score;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneSearchHighlightGradientFormatter)

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightGradientFormatter_initWithFloat_withNSString_withNSString_withNSString_withNSString_(OrgApacheLuceneSearchHighlightGradientFormatter *self, jfloat maxScore, NSString *minForegroundColor, NSString *maxForegroundColor, NSString *minBackgroundColor, NSString *maxBackgroundColor);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightGradientFormatter *new_OrgApacheLuceneSearchHighlightGradientFormatter_initWithFloat_withNSString_withNSString_withNSString_withNSString_(jfloat maxScore, NSString *minForegroundColor, NSString *maxForegroundColor, NSString *minBackgroundColor, NSString *maxBackgroundColor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightGradientFormatter *create_OrgApacheLuceneSearchHighlightGradientFormatter_initWithFloat_withNSString_withNSString_withNSString_withNSString_(jfloat maxScore, NSString *minForegroundColor, NSString *maxForegroundColor, NSString *minBackgroundColor, NSString *maxBackgroundColor);

FOUNDATION_EXPORT jint OrgApacheLuceneSearchHighlightGradientFormatter_hexToIntWithNSString_(NSString *hex);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchHighlightGradientFormatter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightGradientFormatter")
