//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/WeightedSpanTermExtractor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor")
#ifdef RESTRICT_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor

#if !defined (OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_) && (INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor || defined(INCLUDE_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor))
#define OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_

@class OrgApacheLuceneAnalysisTokenStream;
@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchQuery;
@protocol JavaUtilMap;

@interface OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)defaultField;

- (jboolean)getExpandMultiTermQuery;

- (OrgApacheLuceneAnalysisTokenStream *)getTokenStream;

- (id<JavaUtilMap>)getWeightedSpanTermsWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                               withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)tokenStream;

- (id<JavaUtilMap>)getWeightedSpanTermsWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                               withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)tokenStream
                                                         withNSString:(NSString *)fieldName;

- (id<JavaUtilMap>)getWeightedSpanTermsWithScoresWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)query
                                         withOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)tokenStream
                                                                   withNSString:(NSString *)fieldName
                                            withOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (jboolean)isCachedTokenStream;

- (void)setExpandMultiTermQueryWithBoolean:(jboolean)expandMultiTermQuery;

- (void)setWrapIfNotCachingTokenFilterWithBoolean:(jboolean)wrap;

#pragma mark Protected

- (void)setMaxDocCharsToAnalyzeWithInt:(jint)maxDocCharsToAnalyze;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor)

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_init(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *new_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *create_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_init();

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_initWithNSString_(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *self, NSString *defaultField);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *new_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_initWithNSString_(NSString *defaultField) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor *create_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_initWithNSString_(NSString *defaultField);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor)

#endif

#if !defined (OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader_) && (INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor || defined(INCLUDE_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader))
#define OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader_

#define RESTRICT_OrgApacheLuceneIndexFilterIndexReader 1
#define INCLUDE_OrgApacheLuceneIndexFilterIndexReader 1
#include "org/apache/lucene/index/FilterIndexReader.h"

@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneIndexTermEnum;

@interface OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader : OrgApacheLuceneIndexFilterIndexReader {
 @public
  NSString *field_;
}

#pragma mark Public

- (OrgApacheLuceneIndexTermEnum *)termsWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)t;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader, field_, NSString *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader_init(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader *new_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader *create_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor_FakeReader)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightWeightedSpanTermExtractor")
