//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/DuplicateFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchDuplicateFilter")
#ifdef RESTRICT_OrgApacheLuceneSearchDuplicateFilter
#define INCLUDE_ALL_OrgApacheLuceneSearchDuplicateFilter 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchDuplicateFilter 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchDuplicateFilter

#if !defined (OrgApacheLuceneSearchDuplicateFilter_) && (INCLUDE_ALL_OrgApacheLuceneSearchDuplicateFilter || defined(INCLUDE_OrgApacheLuceneSearchDuplicateFilter))
#define OrgApacheLuceneSearchDuplicateFilter_

#define RESTRICT_OrgApacheLuceneSearchFilter 1
#define INCLUDE_OrgApacheLuceneSearchFilter 1
#include "org/apache/lucene/search/Filter.h"

@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchDocIdSet;

@interface OrgApacheLuceneSearchDuplicateFilter : OrgApacheLuceneSearchFilter {
 @public
  NSString *fieldName_;
  jint keepMode_;
  jint processingMode_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)fieldName;

- (instancetype)initWithNSString:(NSString *)fieldName
                         withInt:(jint)keepMode
                         withInt:(jint)processingMode;

- (jboolean)isEqual:(id)obj;

- (OrgApacheLuceneSearchDocIdSet *)getDocIdSetWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (NSString *)getFieldName;

- (jint)getKeepMode;

- (jint)getProcessingMode;

- (NSUInteger)hash;

- (void)setFieldNameWithNSString:(NSString *)fieldName;

- (void)setKeepModeWithInt:(jint)keepMode;

- (void)setProcessingModeWithInt:(jint)processingMode;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchDuplicateFilter)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchDuplicateFilter, fieldName_, NSString *)

inline jint OrgApacheLuceneSearchDuplicateFilter_get_KM_USE_FIRST_OCCURRENCE();
#define OrgApacheLuceneSearchDuplicateFilter_KM_USE_FIRST_OCCURRENCE 1
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchDuplicateFilter, KM_USE_FIRST_OCCURRENCE, jint)

inline jint OrgApacheLuceneSearchDuplicateFilter_get_KM_USE_LAST_OCCURRENCE();
#define OrgApacheLuceneSearchDuplicateFilter_KM_USE_LAST_OCCURRENCE 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchDuplicateFilter, KM_USE_LAST_OCCURRENCE, jint)

inline jint OrgApacheLuceneSearchDuplicateFilter_get_PM_FULL_VALIDATION();
#define OrgApacheLuceneSearchDuplicateFilter_PM_FULL_VALIDATION 1
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchDuplicateFilter, PM_FULL_VALIDATION, jint)

inline jint OrgApacheLuceneSearchDuplicateFilter_get_PM_FAST_INVALIDATION();
#define OrgApacheLuceneSearchDuplicateFilter_PM_FAST_INVALIDATION 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchDuplicateFilter, PM_FAST_INVALIDATION, jint)

FOUNDATION_EXPORT void OrgApacheLuceneSearchDuplicateFilter_initWithNSString_(OrgApacheLuceneSearchDuplicateFilter *self, NSString *fieldName);

FOUNDATION_EXPORT OrgApacheLuceneSearchDuplicateFilter *new_OrgApacheLuceneSearchDuplicateFilter_initWithNSString_(NSString *fieldName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchDuplicateFilter *create_OrgApacheLuceneSearchDuplicateFilter_initWithNSString_(NSString *fieldName);

FOUNDATION_EXPORT void OrgApacheLuceneSearchDuplicateFilter_initWithNSString_withInt_withInt_(OrgApacheLuceneSearchDuplicateFilter *self, NSString *fieldName, jint keepMode, jint processingMode);

FOUNDATION_EXPORT OrgApacheLuceneSearchDuplicateFilter *new_OrgApacheLuceneSearchDuplicateFilter_initWithNSString_withInt_withInt_(NSString *fieldName, jint keepMode, jint processingMode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchDuplicateFilter *create_OrgApacheLuceneSearchDuplicateFilter_initWithNSString_withInt_withInt_(NSString *fieldName, jint keepMode, jint processingMode);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchDuplicateFilter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchDuplicateFilter")
