//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/FilterClause.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchFilterClause")
#ifdef RESTRICT_OrgApacheLuceneSearchFilterClause
#define INCLUDE_ALL_OrgApacheLuceneSearchFilterClause 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchFilterClause 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchFilterClause

#if !defined (OrgApacheLuceneSearchFilterClause_) && (INCLUDE_ALL_OrgApacheLuceneSearchFilterClause || defined(INCLUDE_OrgApacheLuceneSearchFilterClause))
#define OrgApacheLuceneSearchFilterClause_

@class OrgApacheLuceneSearchBooleanClause_Occur;
@class OrgApacheLuceneSearchFilter;

@interface OrgApacheLuceneSearchFilterClause : NSObject

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchFilter:(OrgApacheLuceneSearchFilter *)filter
       withOrgApacheLuceneSearchBooleanClause_Occur:(OrgApacheLuceneSearchBooleanClause_Occur *)occur;

- (jboolean)isEqual:(id)o;

- (OrgApacheLuceneSearchFilter *)getFilter;

- (OrgApacheLuceneSearchBooleanClause_Occur *)getOccur;

- (NSUInteger)hash;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchFilterClause)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilterClause *self, OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur);

FOUNDATION_EXPORT OrgApacheLuceneSearchFilterClause *new_OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchFilterClause *create_OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFilterClause)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchFilterClause")
