//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/FuzzyLikeThisQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchFuzzyLikeThisQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchFuzzyLikeThisQuery

#if !defined (OrgApacheLuceneSearchFuzzyLikeThisQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery || defined(INCLUDE_OrgApacheLuceneSearchFuzzyLikeThisQuery))
#define OrgApacheLuceneSearchFuzzyLikeThisQuery_

#define RESTRICT_OrgApacheLuceneSearchQuery 1
#define INCLUDE_OrgApacheLuceneSearchQuery 1
#include "org/apache/lucene/search/Query.h"

@class JavaUtilArrayList;
@class OrgApacheLuceneAnalysisAnalyzer;
@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue;
@class OrgApacheLuceneSearchSimilarity;

@interface OrgApacheLuceneSearchFuzzyLikeThisQuery : OrgApacheLuceneSearchQuery {
 @public
  OrgApacheLuceneSearchQuery *rewrittenQuery_;
  JavaUtilArrayList *fieldVals_;
  OrgApacheLuceneAnalysisAnalyzer *analyzer_;
  OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue *q_;
  jint MAX_VARIANTS_PER_TERM_;
  jboolean ignoreTF_;
}

#pragma mark Public

- (instancetype)initWithInt:(jint)maxNumTerms
withOrgApacheLuceneAnalysisAnalyzer:(OrgApacheLuceneAnalysisAnalyzer *)analyzer;

- (void)addTermsWithNSString:(NSString *)queryString
                withNSString:(NSString *)fieldName
                   withFloat:(jfloat)minSimilarity
                     withInt:(jint)prefixLength;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (jboolean)isIgnoreTF;

- (OrgApacheLuceneSearchQuery *)rewriteWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (void)setIgnoreTFWithBoolean:(jboolean)ignoreTF;

- (NSString *)toStringWithNSString:(NSString *)field;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneSearchFuzzyLikeThisQuery)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery, rewrittenQuery_, OrgApacheLuceneSearchQuery *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery, fieldVals_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery, analyzer_, OrgApacheLuceneAnalysisAnalyzer *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery, q_, OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue *)

inline OrgApacheLuceneSearchSimilarity *OrgApacheLuceneSearchFuzzyLikeThisQuery_get_sim();
inline OrgApacheLuceneSearchSimilarity *OrgApacheLuceneSearchFuzzyLikeThisQuery_set_sim(OrgApacheLuceneSearchSimilarity *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgApacheLuceneSearchSimilarity *OrgApacheLuceneSearchFuzzyLikeThisQuery_sim;
J2OBJC_STATIC_FIELD_OBJ(OrgApacheLuceneSearchFuzzyLikeThisQuery, sim, OrgApacheLuceneSearchSimilarity *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFuzzyLikeThisQuery_initWithInt_withOrgApacheLuceneAnalysisAnalyzer_(OrgApacheLuceneSearchFuzzyLikeThisQuery *self, jint maxNumTerms, OrgApacheLuceneAnalysisAnalyzer *analyzer);

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery *new_OrgApacheLuceneSearchFuzzyLikeThisQuery_initWithInt_withOrgApacheLuceneAnalysisAnalyzer_(jint maxNumTerms, OrgApacheLuceneAnalysisAnalyzer *analyzer) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery *create_OrgApacheLuceneSearchFuzzyLikeThisQuery_initWithInt_withOrgApacheLuceneAnalysisAnalyzer_(jint maxNumTerms, OrgApacheLuceneAnalysisAnalyzer *analyzer);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFuzzyLikeThisQuery)

#endif

#if !defined (OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals_) && (INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery || defined(INCLUDE_OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals))
#define OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals_

@class OrgApacheLuceneSearchFuzzyLikeThisQuery;

@interface OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals : NSObject {
 @public
  NSString *queryString_;
  NSString *fieldName_;
  jfloat minSimilarity_;
  jint prefixLength_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchFuzzyLikeThisQuery:(OrgApacheLuceneSearchFuzzyLikeThisQuery *)outer$
                                                   withNSString:(NSString *)name
                                                      withFloat:(jfloat)similarity
                                                        withInt:(jint)length
                                                   withNSString:(NSString *)queryString;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals, queryString_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals, fieldName_, NSString *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals_initWithOrgApacheLuceneSearchFuzzyLikeThisQuery_withNSString_withFloat_withInt_withNSString_(OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals *self, OrgApacheLuceneSearchFuzzyLikeThisQuery *outer$, NSString *name, jfloat similarity, jint length, NSString *queryString);

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals *new_OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals_initWithOrgApacheLuceneSearchFuzzyLikeThisQuery_withNSString_withFloat_withInt_withNSString_(OrgApacheLuceneSearchFuzzyLikeThisQuery *outer$, NSString *name, jfloat similarity, jint length, NSString *queryString) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals *create_OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals_initWithOrgApacheLuceneSearchFuzzyLikeThisQuery_withNSString_withFloat_withInt_withNSString_(OrgApacheLuceneSearchFuzzyLikeThisQuery *outer$, NSString *name, jfloat similarity, jint length, NSString *queryString);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFuzzyLikeThisQuery_FieldVals)

#endif

#if !defined (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm_) && (INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery || defined(INCLUDE_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm))
#define OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm_

@class OrgApacheLuceneIndexTerm;

@interface OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm : NSObject {
 @public
  OrgApacheLuceneIndexTerm *term_;
  jfloat score_;
  OrgApacheLuceneIndexTerm *fuzziedSourceTerm_;
}

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
                                       withFloat:(jfloat)score
                    withOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)fuzziedSourceTerm;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm, term_, OrgApacheLuceneIndexTerm *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm, fuzziedSourceTerm_, OrgApacheLuceneIndexTerm *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm_initWithOrgApacheLuceneIndexTerm_withFloat_withOrgApacheLuceneIndexTerm_(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *self, OrgApacheLuceneIndexTerm *term, jfloat score, OrgApacheLuceneIndexTerm *fuzziedSourceTerm);

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *new_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm_initWithOrgApacheLuceneIndexTerm_withFloat_withOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term, jfloat score, OrgApacheLuceneIndexTerm *fuzziedSourceTerm) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *create_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm_initWithOrgApacheLuceneIndexTerm_withFloat_withOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term, jfloat score, OrgApacheLuceneIndexTerm *fuzziedSourceTerm);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm)

#endif

#if !defined (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue_) && (INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery || defined(INCLUDE_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue))
#define OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue_

#define RESTRICT_OrgApacheLuceneUtilPriorityQueue 1
#define INCLUDE_OrgApacheLuceneUtilPriorityQueue 1
#include "org/apache/lucene/util/PriorityQueue.h"

@class OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm;

@interface OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue : OrgApacheLuceneUtilPriorityQueue

#pragma mark Public

- (instancetype)initWithInt:(jint)size;

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)addWithId:(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)arg0;

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)insertWithOverflowWithId:(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)arg0;

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)pop;

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)top;

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)updateTop;

#pragma mark Protected

- (OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)getSentinelObject;

- (jboolean)lessThanWithId:(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)termA
                    withId:(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTerm *)termB;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue)

FOUNDATION_EXPORT void OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue_initWithInt_(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue *self, jint size);

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue *new_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue_initWithInt_(jint size) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue *create_OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue_initWithInt_(jint size);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchFuzzyLikeThisQuery_ScoreTermQueue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchFuzzyLikeThisQuery")
