//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/BooleanFilter.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/Iterable.h"
#include "java/lang/StringBuilder.h"
#include "java/util/ArrayList.h"
#include "java/util/Iterator.h"
#include "java/util/List.h"
#include "java/util/Spliterator.h"
#include "java/util/function/Consumer.h"
#include "org/apache/lucene/index/IndexReader.h"
#include "org/apache/lucene/search/BooleanClause.h"
#include "org/apache/lucene/search/BooleanFilter.h"
#include "org/apache/lucene/search/DocIdSet.h"
#include "org/apache/lucene/search/DocIdSetIterator.h"
#include "org/apache/lucene/search/Filter.h"
#include "org/apache/lucene/search/FilterClause.h"
#include "org/apache/lucene/util/FixedBitSet.h"

@interface OrgApacheLuceneSearchBooleanFilter () {
 @public
  id<JavaUtilList> clauses_;
}

+ (OrgApacheLuceneSearchDocIdSetIterator *)getDISIWithOrgApacheLuceneSearchFilter:(OrgApacheLuceneSearchFilter *)filter
                                              withOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchBooleanFilter, clauses_, id<JavaUtilList>)

__attribute__((unused)) static OrgApacheLuceneSearchDocIdSetIterator *OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneIndexIndexReader *reader);

@implementation OrgApacheLuceneSearchBooleanFilter

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneSearchBooleanFilter_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (OrgApacheLuceneSearchDocIdSet *)getDocIdSetWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader {
  OrgApacheLuceneUtilFixedBitSet *res = nil;
  for (OrgApacheLuceneSearchFilterClause * __strong fc in nil_chk(clauses_)) {
    if ([((OrgApacheLuceneSearchFilterClause *) nil_chk(fc)) getOccur] == JreLoadEnum(OrgApacheLuceneSearchBooleanClause_Occur, SHOULD)) {
      OrgApacheLuceneSearchDocIdSetIterator *disi = OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_([fc getFilter], reader);
      if (disi == nil) continue;
      if (res == nil) {
        res = new_OrgApacheLuceneUtilFixedBitSet_initWithInt_([((OrgApacheLuceneIndexIndexReader *) nil_chk(reader)) maxDoc]);
      }
      [res or__WithOrgApacheLuceneSearchDocIdSetIterator:disi];
    }
  }
  for (OrgApacheLuceneSearchFilterClause * __strong fc in clauses_) {
    if ([((OrgApacheLuceneSearchFilterClause *) nil_chk(fc)) getOccur] == JreLoadEnum(OrgApacheLuceneSearchBooleanClause_Occur, MUST_NOT)) {
      if (res == nil) {
        res = new_OrgApacheLuceneUtilFixedBitSet_initWithInt_([((OrgApacheLuceneIndexIndexReader *) nil_chk(reader)) maxDoc]);
        [res setWithInt:0 withInt:[reader maxDoc]];
      }
      OrgApacheLuceneSearchDocIdSetIterator *disi = OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_([fc getFilter], reader);
      if (disi != nil) {
        [res andNotWithOrgApacheLuceneSearchDocIdSetIterator:disi];
      }
    }
  }
  for (OrgApacheLuceneSearchFilterClause * __strong fc in clauses_) {
    if ([((OrgApacheLuceneSearchFilterClause *) nil_chk(fc)) getOccur] == JreLoadEnum(OrgApacheLuceneSearchBooleanClause_Occur, MUST)) {
      OrgApacheLuceneSearchDocIdSetIterator *disi = OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_([fc getFilter], reader);
      if (disi == nil) {
        return JreLoadStatic(OrgApacheLuceneSearchDocIdSet, EMPTY_DOCIDSET);
      }
      if (res == nil) {
        res = new_OrgApacheLuceneUtilFixedBitSet_initWithInt_([((OrgApacheLuceneIndexIndexReader *) nil_chk(reader)) maxDoc]);
        [res or__WithOrgApacheLuceneSearchDocIdSetIterator:disi];
      }
      else {
        [res and__WithOrgApacheLuceneSearchDocIdSetIterator:disi];
      }
    }
  }
  return res != nil ? res : JreLoadStatic(OrgApacheLuceneSearchDocIdSet, EMPTY_DOCIDSET);
}

+ (OrgApacheLuceneSearchDocIdSetIterator *)getDISIWithOrgApacheLuceneSearchFilter:(OrgApacheLuceneSearchFilter *)filter
                                              withOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader {
  return OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_(filter, reader);
}

- (void)addWithOrgApacheLuceneSearchFilterClause:(OrgApacheLuceneSearchFilterClause *)filterClause {
  [((id<JavaUtilList>) nil_chk(clauses_)) addWithId:filterClause];
}

- (void)addWithOrgApacheLuceneSearchFilter:(OrgApacheLuceneSearchFilter *)filter
withOrgApacheLuceneSearchBooleanClause_Occur:(OrgApacheLuceneSearchBooleanClause_Occur *)occur {
  [self addWithOrgApacheLuceneSearchFilterClause:new_OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(filter, occur)];
}

- (id<JavaUtilList>)clauses {
  return clauses_;
}

- (id<JavaUtilIterator>)iterator {
  return [((id<JavaUtilList>) nil_chk([self clauses])) iterator];
}

- (jboolean)isEqual:(id)obj {
  if (self == obj) {
    return true;
  }
  if ((obj == nil) || ([nil_chk(obj) java_getClass] != [self java_getClass])) {
    return false;
  }
  OrgApacheLuceneSearchBooleanFilter *other = (OrgApacheLuceneSearchBooleanFilter *) cast_chk(obj, [OrgApacheLuceneSearchBooleanFilter class]);
  return [((id<JavaUtilList>) nil_chk(clauses_)) isEqual:((OrgApacheLuceneSearchBooleanFilter *) nil_chk(other))->clauses_];
}

- (NSUInteger)hash {
  return 657153718 ^ ((jint) [((id<JavaUtilList>) nil_chk(clauses_)) hash]);
}

- (NSString *)description {
  JavaLangStringBuilder *buffer = new_JavaLangStringBuilder_initWithNSString_(@"BooleanFilter(");
  jint minLen = [buffer java_length];
  for (OrgApacheLuceneSearchFilterClause * __strong c in nil_chk(clauses_)) {
    if ([buffer java_length] > minLen) {
      (void) [buffer appendWithChar:' '];
    }
    (void) [buffer appendWithId:c];
  }
  return [((JavaLangStringBuilder *) nil_chk([buffer appendWithChar:')'])) description];
}

- (void)forEachWithJavaUtilFunctionConsumer:(id<JavaUtilFunctionConsumer>)arg0 {
  JavaLangIterable_forEachWithJavaUtilFunctionConsumer_(self, arg0);
}

- (id<JavaUtilSpliterator>)spliterator {
  return JavaLangIterable_spliterator(self);
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchDocIdSet;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchDocIdSetIterator;", 0xa, 3, 4, 2, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "V", 0x11, 5, 7, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 8, -1, -1 },
    { NULL, "LJavaUtilIterator;", 0x11, -1, -1, -1, 9, -1, -1 },
    { NULL, "Z", 0x1, 10, 11, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 12, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 13, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(getDocIdSetWithOrgApacheLuceneIndexIndexReader:);
  methods[2].selector = @selector(getDISIWithOrgApacheLuceneSearchFilter:withOrgApacheLuceneIndexIndexReader:);
  methods[3].selector = @selector(addWithOrgApacheLuceneSearchFilterClause:);
  methods[4].selector = @selector(addWithOrgApacheLuceneSearchFilter:withOrgApacheLuceneSearchBooleanClause_Occur:);
  methods[5].selector = @selector(clauses);
  methods[6].selector = @selector(iterator);
  methods[7].selector = @selector(isEqual:);
  methods[8].selector = @selector(hash);
  methods[9].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "clauses_", "LJavaUtilList;", .constantValue.asLong = 0, 0x12, -1, -1, 14, -1 },
  };
  static const void *ptrTable[] = { "getDocIdSet", "LOrgApacheLuceneIndexIndexReader;", "LJavaIoIOException;", "getDISI", "LOrgApacheLuceneSearchFilter;LOrgApacheLuceneIndexIndexReader;", "add", "LOrgApacheLuceneSearchFilterClause;", "LOrgApacheLuceneSearchFilter;LOrgApacheLuceneSearchBooleanClause_Occur;", "()Ljava/util/List<Lorg/apache/lucene/search/FilterClause;>;", "()Ljava/util/Iterator<Lorg/apache/lucene/search/FilterClause;>;", "equals", "LNSObject;", "hashCode", "toString", "Ljava/util/List<Lorg/apache/lucene/search/FilterClause;>;", "Lorg/apache/lucene/search/Filter;Ljava/lang/Iterable<Lorg/apache/lucene/search/FilterClause;>;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchBooleanFilter = { "BooleanFilter", "org.apache.lucene.search", ptrTable, methods, fields, 7, 0x1, 10, 1, -1, -1, -1, 15, -1 };
  return &_OrgApacheLuceneSearchBooleanFilter;
}

@end

void OrgApacheLuceneSearchBooleanFilter_init(OrgApacheLuceneSearchBooleanFilter *self) {
  OrgApacheLuceneSearchFilter_init(self);
  self->clauses_ = new_JavaUtilArrayList_init();
}

OrgApacheLuceneSearchBooleanFilter *new_OrgApacheLuceneSearchBooleanFilter_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchBooleanFilter, init)
}

OrgApacheLuceneSearchBooleanFilter *create_OrgApacheLuceneSearchBooleanFilter_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchBooleanFilter, init)
}

OrgApacheLuceneSearchDocIdSetIterator *OrgApacheLuceneSearchBooleanFilter_getDISIWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneIndexIndexReader_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneIndexIndexReader *reader) {
  OrgApacheLuceneSearchBooleanFilter_initialize();
  OrgApacheLuceneSearchDocIdSet *set = [((OrgApacheLuceneSearchFilter *) nil_chk(filter)) getDocIdSetWithOrgApacheLuceneIndexIndexReader:reader];
  return (set == nil || set == JreLoadStatic(OrgApacheLuceneSearchDocIdSet, EMPTY_DOCIDSET)) ? nil : [((OrgApacheLuceneSearchDocIdSet *) nil_chk(set)) iterator];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchBooleanFilter)
