//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/FilterClause.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/BooleanClause.h"
#include "org/apache/lucene/search/Filter.h"
#include "org/apache/lucene/search/FilterClause.h"

@interface OrgApacheLuceneSearchFilterClause () {
 @public
  OrgApacheLuceneSearchBooleanClause_Occur *occur_;
  OrgApacheLuceneSearchFilter *filter_;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFilterClause, occur_, OrgApacheLuceneSearchBooleanClause_Occur *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchFilterClause, filter_, OrgApacheLuceneSearchFilter *)

@implementation OrgApacheLuceneSearchFilterClause

- (instancetype)initWithOrgApacheLuceneSearchFilter:(OrgApacheLuceneSearchFilter *)filter
       withOrgApacheLuceneSearchBooleanClause_Occur:(OrgApacheLuceneSearchBooleanClause_Occur *)occur {
  OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(self, filter, occur);
  return self;
}

- (OrgApacheLuceneSearchFilter *)getFilter {
  return filter_;
}

- (OrgApacheLuceneSearchBooleanClause_Occur *)getOccur {
  return occur_;
}

- (jboolean)isEqual:(id)o {
  if (o == self) return true;
  if (o == nil || !([o isKindOfClass:[OrgApacheLuceneSearchFilterClause class]])) return false;
  OrgApacheLuceneSearchFilterClause *other = (OrgApacheLuceneSearchFilterClause *) cast_chk(o, [OrgApacheLuceneSearchFilterClause class]);
  return [((OrgApacheLuceneSearchFilter *) nil_chk(self->filter_)) isEqual:other->filter_] && self->occur_ == other->occur_;
}

- (NSUInteger)hash {
  return ((jint) [((OrgApacheLuceneSearchFilter *) nil_chk(filter_)) hash]) ^ ((jint) [((OrgApacheLuceneSearchBooleanClause_Occur *) nil_chk(occur_)) hash]);
}

- (NSString *)description {
  return JreStrcat("$$", [((OrgApacheLuceneSearchBooleanClause_Occur *) nil_chk(occur_)) description], [((OrgApacheLuceneSearchFilter *) nil_chk(filter_)) description]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchFilter;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchBooleanClause_Occur;", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "I", 0x1, 3, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 4, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchFilter:withOrgApacheLuceneSearchBooleanClause_Occur:);
  methods[1].selector = @selector(getFilter);
  methods[2].selector = @selector(getOccur);
  methods[3].selector = @selector(isEqual:);
  methods[4].selector = @selector(hash);
  methods[5].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "occur_", "LOrgApacheLuceneSearchBooleanClause_Occur;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "filter_", "LOrgApacheLuceneSearchFilter;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneSearchFilter;LOrgApacheLuceneSearchBooleanClause_Occur;", "equals", "LNSObject;", "hashCode", "toString" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchFilterClause = { "FilterClause", "org.apache.lucene.search", ptrTable, methods, fields, 7, 0x11, 6, 2, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchFilterClause;
}

@end

void OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilterClause *self, OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur) {
  NSObject_init(self);
  self->occur_ = occur;
  self->filter_ = filter;
}

OrgApacheLuceneSearchFilterClause *new_OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchFilterClause, initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_, filter, occur)
}

OrgApacheLuceneSearchFilterClause *create_OrgApacheLuceneSearchFilterClause_initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_(OrgApacheLuceneSearchFilter *filter, OrgApacheLuceneSearchBooleanClause_Occur *occur) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchFilterClause, initWithOrgApacheLuceneSearchFilter_withOrgApacheLuceneSearchBooleanClause_Occur_, filter, occur)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchFilterClause)
