//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/regexp/ReaderCharacterIterator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheRegexpReaderCharacterIterator")
#ifdef RESTRICT_OrgApacheRegexpReaderCharacterIterator
#define INCLUDE_ALL_OrgApacheRegexpReaderCharacterIterator 0
#else
#define INCLUDE_ALL_OrgApacheRegexpReaderCharacterIterator 1
#endif
#undef RESTRICT_OrgApacheRegexpReaderCharacterIterator

#if !defined (OrgApacheRegexpReaderCharacterIterator_) && (INCLUDE_ALL_OrgApacheRegexpReaderCharacterIterator || defined(INCLUDE_OrgApacheRegexpReaderCharacterIterator))
#define OrgApacheRegexpReaderCharacterIterator_

#define RESTRICT_OrgApacheRegexpCharacterIterator 1
#define INCLUDE_OrgApacheRegexpCharacterIterator 1
#include "org/apache/regexp/CharacterIterator.h"

@class JavaIoReader;

@interface OrgApacheRegexpReaderCharacterIterator : NSObject < OrgApacheRegexpCharacterIterator >

#pragma mark Public

- (instancetype)initWithJavaIoReader:(JavaIoReader *)reader;

- (jchar)charAtWithInt:(jint)pos;

- (jboolean)isEndWithInt:(jint)pos;

- (NSString *)substringWithInt:(jint)beginIndex;

- (NSString *)substringWithInt:(jint)beginIndex
                       withInt:(jint)endIndex;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheRegexpReaderCharacterIterator)

FOUNDATION_EXPORT void OrgApacheRegexpReaderCharacterIterator_initWithJavaIoReader_(OrgApacheRegexpReaderCharacterIterator *self, JavaIoReader *reader);

FOUNDATION_EXPORT OrgApacheRegexpReaderCharacterIterator *new_OrgApacheRegexpReaderCharacterIterator_initWithJavaIoReader_(JavaIoReader *reader) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheRegexpReaderCharacterIterator *create_OrgApacheRegexpReaderCharacterIterator_initWithJavaIoReader_(JavaIoReader *reader);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheRegexpReaderCharacterIterator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheRegexpReaderCharacterIterator")
