//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/regexp/StringCharacterIterator.java
//

#include "J2ObjC_source.h"
#include "org/apache/regexp/StringCharacterIterator.h"

@interface OrgApacheRegexpStringCharacterIterator () {
 @public
  NSString *src_;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheRegexpStringCharacterIterator, src_, NSString *)

@implementation OrgApacheRegexpStringCharacterIterator

- (instancetype)initWithNSString:(NSString *)src {
  OrgApacheRegexpStringCharacterIterator_initWithNSString_(self, src);
  return self;
}

- (NSString *)substringWithInt:(jint)beginIndex
                       withInt:(jint)endIndex {
  return [((NSString *) nil_chk(src_)) java_substring:beginIndex endIndex:endIndex];
}

- (NSString *)substringWithInt:(jint)beginIndex {
  return [((NSString *) nil_chk(src_)) java_substring:beginIndex];
}

- (jchar)charAtWithInt:(jint)pos {
  return [((NSString *) nil_chk(src_)) charAtWithInt:pos];
}

- (jboolean)isEndWithInt:(jint)pos {
  return (pos >= [((NSString *) nil_chk(src_)) java_length]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, 2, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 1, 3, -1, -1, -1, -1 },
    { NULL, "C", 0x1, 4, 3, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 5, 3, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(substringWithInt:withInt:);
  methods[2].selector = @selector(substringWithInt:);
  methods[3].selector = @selector(charAtWithInt:);
  methods[4].selector = @selector(isEndWithInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "src_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "substring", "II", "I", "charAt", "isEnd" };
  static const J2ObjcClassInfo _OrgApacheRegexpStringCharacterIterator = { "StringCharacterIterator", "org.apache.regexp", ptrTable, methods, fields, 7, 0x11, 5, 1, -1, -1, -1, -1, -1 };
  return &_OrgApacheRegexpStringCharacterIterator;
}

@end

void OrgApacheRegexpStringCharacterIterator_initWithNSString_(OrgApacheRegexpStringCharacterIterator *self, NSString *src) {
  NSObject_init(self);
  self->src_ = src;
}

OrgApacheRegexpStringCharacterIterator *new_OrgApacheRegexpStringCharacterIterator_initWithNSString_(NSString *src) {
  J2OBJC_NEW_IMPL(OrgApacheRegexpStringCharacterIterator, initWithNSString_, src)
}

OrgApacheRegexpStringCharacterIterator *create_OrgApacheRegexpStringCharacterIterator_initWithNSString_(NSString *src) {
  J2OBJC_CREATE_IMPL(OrgApacheRegexpStringCharacterIterator, initWithNSString_, src)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheRegexpStringCharacterIterator)
