//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/regexp/StringCharacterIterator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheRegexpStringCharacterIterator")
#ifdef RESTRICT_OrgApacheRegexpStringCharacterIterator
#define INCLUDE_ALL_OrgApacheRegexpStringCharacterIterator 0
#else
#define INCLUDE_ALL_OrgApacheRegexpStringCharacterIterator 1
#endif
#undef RESTRICT_OrgApacheRegexpStringCharacterIterator

#if !defined (OrgApacheRegexpStringCharacterIterator_) && (INCLUDE_ALL_OrgApacheRegexpStringCharacterIterator || defined(INCLUDE_OrgApacheRegexpStringCharacterIterator))
#define OrgApacheRegexpStringCharacterIterator_

#define RESTRICT_OrgApacheRegexpCharacterIterator 1
#define INCLUDE_OrgApacheRegexpCharacterIterator 1
#include "org/apache/regexp/CharacterIterator.h"

@interface OrgApacheRegexpStringCharacterIterator : NSObject < OrgApacheRegexpCharacterIterator >

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)src;

- (jchar)charAtWithInt:(jint)pos;

- (jboolean)isEndWithInt:(jint)pos;

- (NSString *)substringWithInt:(jint)beginIndex;

- (NSString *)substringWithInt:(jint)beginIndex
                       withInt:(jint)endIndex;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheRegexpStringCharacterIterator)

FOUNDATION_EXPORT void OrgApacheRegexpStringCharacterIterator_initWithNSString_(OrgApacheRegexpStringCharacterIterator *self, NSString *src);

FOUNDATION_EXPORT OrgApacheRegexpStringCharacterIterator *new_OrgApacheRegexpStringCharacterIterator_initWithNSString_(NSString *src) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheRegexpStringCharacterIterator *create_OrgApacheRegexpStringCharacterIterator_initWithNSString_(NSString *src);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheRegexpStringCharacterIterator)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheRegexpStringCharacterIterator")
