//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/DefaultEncoder.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/highlight/DefaultEncoder.h"

@implementation OrgApacheLuceneSearchHighlightDefaultEncoder

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgApacheLuceneSearchHighlightDefaultEncoder_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)encodeTextWithNSString:(NSString *)originalText {
  return originalText;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(encodeTextWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "encodeText", "LNSString;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchHighlightDefaultEncoder = { "DefaultEncoder", "org.apache.lucene.search.highlight", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchHighlightDefaultEncoder;
}

@end

void OrgApacheLuceneSearchHighlightDefaultEncoder_init(OrgApacheLuceneSearchHighlightDefaultEncoder *self) {
  NSObject_init(self);
}

OrgApacheLuceneSearchHighlightDefaultEncoder *new_OrgApacheLuceneSearchHighlightDefaultEncoder_init() {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchHighlightDefaultEncoder, init)
}

OrgApacheLuceneSearchHighlightDefaultEncoder *create_OrgApacheLuceneSearchHighlightDefaultEncoder_init() {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchHighlightDefaultEncoder, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchHighlightDefaultEncoder)
