//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/InvalidTokenOffsetsException.java
//

#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "org/apache/lucene/search/highlight/InvalidTokenOffsetsException.h"

@implementation OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException

- (instancetype)initWithNSString:(NSString *)message {
  OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException = { "InvalidTokenOffsetsException", "org.apache.lucene.search.highlight", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException;
}

@end

void OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException_initWithNSString_(OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException *self, NSString *message) {
  JavaLangException_initWithNSString_(self, message);
}

OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException *new_OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException, initWithNSString_, message)
}

OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException *create_OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException, initWithNSString_, message)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchHighlightInvalidTokenOffsetsException)
