//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/Scorer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightScorer")
#ifdef RESTRICT_OrgApacheLuceneSearchHighlightScorer
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightScorer 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchHighlightScorer 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchHighlightScorer

#if !defined (OrgApacheLuceneSearchHighlightScorer_) && (INCLUDE_ALL_OrgApacheLuceneSearchHighlightScorer || defined(INCLUDE_OrgApacheLuceneSearchHighlightScorer))
#define OrgApacheLuceneSearchHighlightScorer_

@class OrgApacheLuceneAnalysisTokenStream;
@class OrgApacheLuceneSearchHighlightTextFragment;

@protocol OrgApacheLuceneSearchHighlightScorer < JavaObject >

- (OrgApacheLuceneAnalysisTokenStream *)init__WithOrgApacheLuceneAnalysisTokenStream:(OrgApacheLuceneAnalysisTokenStream *)tokenStream OBJC_METHOD_FAMILY_NONE;

- (void)startFragmentWithOrgApacheLuceneSearchHighlightTextFragment:(OrgApacheLuceneSearchHighlightTextFragment *)newFragment;

- (jfloat)getTokenScore;

- (jfloat)getFragmentScore;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchHighlightScorer)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchHighlightScorer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchHighlightScorer")
