//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/BaseFragmentsBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder")
#ifdef RESTRICT_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder

#if !defined (OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder))
#define OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_

#define RESTRICT_OrgApacheLuceneSearchVectorhighlightFragmentsBuilder 1
#define INCLUDE_OrgApacheLuceneSearchVectorhighlightFragmentsBuilder 1
#include "org/apache/lucene/search/vectorhighlight/FragmentsBuilder.h"

@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangStringBuilder;
@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneSearchVectorhighlightFieldFragList;
@class OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo;
@protocol JavaUtilList;
@protocol OrgApacheLuceneSearchHighlightEncoder;
@protocol OrgApacheLuceneSearchVectorhighlightBoundaryScanner;

@interface OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder : NSObject < OrgApacheLuceneSearchVectorhighlightFragmentsBuilder > {
 @public
  IOSObjectArray *preTags_;
  IOSObjectArray *postTags_;
}

#pragma mark Public

- (NSString *)createFragmentWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                        withInt:(jint)docId
                                                   withNSString:(NSString *)fieldName
          withOrgApacheLuceneSearchVectorhighlightFieldFragList:(OrgApacheLuceneSearchVectorhighlightFieldFragList *)fieldFragList;

- (NSString *)createFragmentWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                        withInt:(jint)docId
                                                   withNSString:(NSString *)fieldName
          withOrgApacheLuceneSearchVectorhighlightFieldFragList:(OrgApacheLuceneSearchVectorhighlightFieldFragList *)fieldFragList
                                              withNSStringArray:(IOSObjectArray *)preTags
                                              withNSStringArray:(IOSObjectArray *)postTags
                      withOrgApacheLuceneSearchHighlightEncoder:(id<OrgApacheLuceneSearchHighlightEncoder>)encoder;

- (IOSObjectArray *)createFragmentsWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                               withInt:(jint)docId
                                                          withNSString:(NSString *)fieldName
                 withOrgApacheLuceneSearchVectorhighlightFieldFragList:(OrgApacheLuceneSearchVectorhighlightFieldFragList *)fieldFragList
                                                               withInt:(jint)maxNumFragments;

- (IOSObjectArray *)createFragmentsWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                               withInt:(jint)docId
                                                          withNSString:(NSString *)fieldName
                 withOrgApacheLuceneSearchVectorhighlightFieldFragList:(OrgApacheLuceneSearchVectorhighlightFieldFragList *)fieldFragList
                                                               withInt:(jint)maxNumFragments
                                                     withNSStringArray:(IOSObjectArray *)preTags
                                                     withNSStringArray:(IOSObjectArray *)postTags
                             withOrgApacheLuceneSearchHighlightEncoder:(id<OrgApacheLuceneSearchHighlightEncoder>)encoder;

- (jchar)getMultiValuedSeparator;

- (id<JavaUtilList>)getWeightedFragInfoListWithJavaUtilList:(id<JavaUtilList>)src;

- (void)setMultiValuedSeparatorWithChar:(jchar)separator;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithOrgApacheLuceneSearchVectorhighlightBoundaryScanner:(id<OrgApacheLuceneSearchVectorhighlightBoundaryScanner>)boundaryScanner;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)preTags
                    withNSStringArray:(IOSObjectArray *)postTags;

- (instancetype)initWithNSStringArray:(IOSObjectArray *)preTags
                    withNSStringArray:(IOSObjectArray *)postTags
withOrgApacheLuceneSearchVectorhighlightBoundaryScanner:(id<OrgApacheLuceneSearchVectorhighlightBoundaryScanner>)boundaryScanner;

- (IOSObjectArray *)getFieldsWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                         withInt:(jint)docId
                                                    withNSString:(NSString *)fieldName;

- (IOSObjectArray *)getFieldValuesWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                                                              withInt:(jint)docId
                                                         withNSString:(NSString *)fieldName;

- (NSString *)getFragmentSourceWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                            withIntArray:(IOSIntArray *)index
                   withOrgApacheLuceneDocumentFieldArray:(IOSObjectArray *)values
                                                 withInt:(jint)startOffset
                                                 withInt:(jint)endOffset;

- (NSString *)getFragmentSourceWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                            withIntArray:(IOSIntArray *)index
                                       withNSStringArray:(IOSObjectArray *)values
                                                 withInt:(jint)startOffset
                                                 withInt:(jint)endOffset;

- (NSString *)getFragmentSourceMSOWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                               withIntArray:(IOSIntArray *)index
                      withOrgApacheLuceneDocumentFieldArray:(IOSObjectArray *)values
                                                    withInt:(jint)startOffset
                                                    withInt:(jint)endOffset
                                               withIntArray:(IOSIntArray *)modifiedStartOffset;

- (NSString *)getPostTagWithInt:(jint)num;

- (NSString *)getPostTagWithNSStringArray:(IOSObjectArray *)postTags
                                  withInt:(jint)num;

- (NSString *)getPreTagWithInt:(jint)num;

- (NSString *)getPreTagWithNSStringArray:(IOSObjectArray *)preTags
                                 withInt:(jint)num;

- (NSString *)makeFragmentWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                       withIntArray:(IOSIntArray *)index
              withOrgApacheLuceneDocumentFieldArray:(IOSObjectArray *)values
withOrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo:(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo *)fragInfo
                                  withNSStringArray:(IOSObjectArray *)preTags
                                  withNSStringArray:(IOSObjectArray *)postTags
          withOrgApacheLuceneSearchHighlightEncoder:(id<OrgApacheLuceneSearchHighlightEncoder>)encoder;

- (NSString *)makeFragmentWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                       withIntArray:(IOSIntArray *)index
                                  withNSStringArray:(IOSObjectArray *)values
withOrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo:(OrgApacheLuceneSearchVectorhighlightFieldFragList_WeightedFragInfo *)fragInfo;

#pragma mark Package-Private

+ (id)checkTagsArgumentWithId:(id)tags;

@end

J2OBJC_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder)

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder, preTags_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder, postTags_, IOSObjectArray *)

inline IOSObjectArray *OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_get_COLORED_PRE_TAGS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_COLORED_PRE_TAGS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder, COLORED_PRE_TAGS, IOSObjectArray *)

inline IOSObjectArray *OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_get_COLORED_POST_TAGS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_COLORED_POST_TAGS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder, COLORED_POST_TAGS, IOSObjectArray *)

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_init(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder *self);

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_initWithNSStringArray_withNSStringArray_(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder *self, IOSObjectArray *preTags, IOSObjectArray *postTags);

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_initWithOrgApacheLuceneSearchVectorhighlightBoundaryScanner_(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder *self, id<OrgApacheLuceneSearchVectorhighlightBoundaryScanner> boundaryScanner);

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_initWithNSStringArray_withNSStringArray_withOrgApacheLuceneSearchVectorhighlightBoundaryScanner_(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder *self, IOSObjectArray *preTags, IOSObjectArray *postTags, id<OrgApacheLuceneSearchVectorhighlightBoundaryScanner> boundaryScanner);

FOUNDATION_EXPORT id OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder_checkTagsArgumentWithId_(id tags);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBaseFragmentsBuilder")
