//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/BoundaryScanner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBoundaryScanner")
#ifdef RESTRICT_OrgApacheLuceneSearchVectorhighlightBoundaryScanner
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBoundaryScanner 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBoundaryScanner 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchVectorhighlightBoundaryScanner

#if !defined (OrgApacheLuceneSearchVectorhighlightBoundaryScanner_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBoundaryScanner || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightBoundaryScanner))
#define OrgApacheLuceneSearchVectorhighlightBoundaryScanner_

@class JavaLangStringBuilder;

@protocol OrgApacheLuceneSearchVectorhighlightBoundaryScanner < JavaObject >

- (jint)findStartOffsetWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                         withInt:(jint)start;

- (jint)findEndOffsetWithJavaLangStringBuilder:(JavaLangStringBuilder *)buffer
                                       withInt:(jint)start;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightBoundaryScanner)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightBoundaryScanner)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightBoundaryScanner")
