//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/FragListBuilder.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/vectorhighlight/FragListBuilder.h"

@interface OrgApacheLuceneSearchVectorhighlightFragListBuilder : NSObject

@end

@implementation OrgApacheLuceneSearchVectorhighlightFragListBuilder

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LOrgApacheLuceneSearchVectorhighlightFieldFragList;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(createFieldFragListWithOrgApacheLuceneSearchVectorhighlightFieldPhraseList:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "createFieldFragList", "LOrgApacheLuceneSearchVectorhighlightFieldPhraseList;I" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchVectorhighlightFragListBuilder = { "FragListBuilder", "org.apache.lucene.search.vectorhighlight", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchVectorhighlightFragListBuilder;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchVectorhighlightFragListBuilder)
