//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/FragmentsBuilder.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/vectorhighlight/FragmentsBuilder.h"

@interface OrgApacheLuceneSearchVectorhighlightFragmentsBuilder : NSObject

@end

@implementation OrgApacheLuceneSearchVectorhighlightFragmentsBuilder

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, 2, -1, -1, -1 },
    { NULL, "[LNSString;", 0x401, 3, 4, 2, -1, -1, -1 },
    { NULL, "LNSString;", 0x401, 0, 5, 2, -1, -1, -1 },
    { NULL, "[LNSString;", 0x401, 3, 6, 2, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(createFragmentWithOrgApacheLuceneIndexIndexReader:withInt:withNSString:withOrgApacheLuceneSearchVectorhighlightFieldFragList:);
  methods[1].selector = @selector(createFragmentsWithOrgApacheLuceneIndexIndexReader:withInt:withNSString:withOrgApacheLuceneSearchVectorhighlightFieldFragList:withInt:);
  methods[2].selector = @selector(createFragmentWithOrgApacheLuceneIndexIndexReader:withInt:withNSString:withOrgApacheLuceneSearchVectorhighlightFieldFragList:withNSStringArray:withNSStringArray:withOrgApacheLuceneSearchHighlightEncoder:);
  methods[3].selector = @selector(createFragmentsWithOrgApacheLuceneIndexIndexReader:withInt:withNSString:withOrgApacheLuceneSearchVectorhighlightFieldFragList:withInt:withNSStringArray:withNSStringArray:withOrgApacheLuceneSearchHighlightEncoder:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "createFragment", "LOrgApacheLuceneIndexIndexReader;ILNSString;LOrgApacheLuceneSearchVectorhighlightFieldFragList;", "LJavaIoIOException;", "createFragments", "LOrgApacheLuceneIndexIndexReader;ILNSString;LOrgApacheLuceneSearchVectorhighlightFieldFragList;I", "LOrgApacheLuceneIndexIndexReader;ILNSString;LOrgApacheLuceneSearchVectorhighlightFieldFragList;[LNSString;[LNSString;LOrgApacheLuceneSearchHighlightEncoder;", "LOrgApacheLuceneIndexIndexReader;ILNSString;LOrgApacheLuceneSearchVectorhighlightFieldFragList;I[LNSString;[LNSString;LOrgApacheLuceneSearchHighlightEncoder;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchVectorhighlightFragmentsBuilder = { "FragmentsBuilder", "org.apache.lucene.search.vectorhighlight", ptrTable, methods, NULL, 7, 0x609, 4, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchVectorhighlightFragmentsBuilder;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchVectorhighlightFragmentsBuilder)
