//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/vectorhighlight/SimpleFragListBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder")
#ifdef RESTRICT_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder

#if !defined (OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_) && (INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder || defined(INCLUDE_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder))
#define OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_

#define RESTRICT_OrgApacheLuceneSearchVectorhighlightFragListBuilder 1
#define INCLUDE_OrgApacheLuceneSearchVectorhighlightFragListBuilder 1
#include "org/apache/lucene/search/vectorhighlight/FragListBuilder.h"

@class OrgApacheLuceneSearchVectorhighlightFieldFragList;
@class OrgApacheLuceneSearchVectorhighlightFieldPhraseList;

@interface OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder : NSObject < OrgApacheLuceneSearchVectorhighlightFragListBuilder > {
 @public
  jint margin_;
  jint minFragCharSize_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)margin;

- (OrgApacheLuceneSearchVectorhighlightFieldFragList *)createFieldFragListWithOrgApacheLuceneSearchVectorhighlightFieldPhraseList:(OrgApacheLuceneSearchVectorhighlightFieldPhraseList *)fieldPhraseList
                                                                                                                          withInt:(jint)fragCharSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder)

inline jint OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_get_MARGIN_DEFAULT();
#define OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_MARGIN_DEFAULT 6
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder, MARGIN_DEFAULT, jint)

inline jint OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_get_MIN_FRAG_CHAR_SIZE_FACTOR();
#define OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_MIN_FRAG_CHAR_SIZE_FACTOR 3
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder, MIN_FRAG_CHAR_SIZE_FACTOR, jint)

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_initWithInt_(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *self, jint margin);

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *new_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_initWithInt_(jint margin) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *create_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_initWithInt_(jint margin);

FOUNDATION_EXPORT void OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_init(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *self);

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *new_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder *create_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder_init();

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchVectorhighlightSimpleFragListBuilder")
