//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/regex/RegexTermEnum.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexTermEnum")
#ifdef RESTRICT_OrgApacheLuceneSearchRegexRegexTermEnum
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexTermEnum 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexTermEnum 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchRegexRegexTermEnum

#if !defined (OrgApacheLuceneSearchRegexRegexTermEnum_) && (INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexTermEnum || defined(INCLUDE_OrgApacheLuceneSearchRegexRegexTermEnum))
#define OrgApacheLuceneSearchRegexRegexTermEnum_

#define RESTRICT_OrgApacheLuceneSearchFilteredTermEnum 1
#define INCLUDE_OrgApacheLuceneSearchFilteredTermEnum 1
#include "org/apache/lucene/search/FilteredTermEnum.h"

@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneIndexTerm;
@protocol OrgApacheLuceneSearchRegexRegexCapabilities;

@interface OrgApacheLuceneSearchRegexRegexTermEnum : OrgApacheLuceneSearchFilteredTermEnum

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader
                           withOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term
        withOrgApacheLuceneSearchRegexRegexCapabilities:(id<OrgApacheLuceneSearchRegexRegexCapabilities>)regexImpl;

- (void)close;

- (jfloat)difference;

- (jboolean)endEnum;

#pragma mark Protected

- (jboolean)termCompareWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchRegexRegexTermEnum)

FOUNDATION_EXPORT void OrgApacheLuceneSearchRegexRegexTermEnum_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchRegexRegexCapabilities_(OrgApacheLuceneSearchRegexRegexTermEnum *self, OrgApacheLuceneIndexIndexReader *reader, OrgApacheLuceneIndexTerm *term, id<OrgApacheLuceneSearchRegexRegexCapabilities> regexImpl);

FOUNDATION_EXPORT OrgApacheLuceneSearchRegexRegexTermEnum *new_OrgApacheLuceneSearchRegexRegexTermEnum_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchRegexRegexCapabilities_(OrgApacheLuceneIndexIndexReader *reader, OrgApacheLuceneIndexTerm *term, id<OrgApacheLuceneSearchRegexRegexCapabilities> regexImpl) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchRegexRegexTermEnum *create_OrgApacheLuceneSearchRegexRegexTermEnum_initWithOrgApacheLuceneIndexIndexReader_withOrgApacheLuceneIndexTerm_withOrgApacheLuceneSearchRegexRegexCapabilities_(OrgApacheLuceneIndexIndexReader *reader, OrgApacheLuceneIndexTerm *term, id<OrgApacheLuceneSearchRegexRegexCapabilities> regexImpl);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchRegexRegexTermEnum)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexTermEnum")
