//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/regex/RegexQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchRegexRegexQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchRegexRegexQuery

#if !defined (OrgApacheLuceneSearchRegexRegexQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQuery || defined(INCLUDE_OrgApacheLuceneSearchRegexRegexQuery))
#define OrgApacheLuceneSearchRegexRegexQuery_

#define RESTRICT_OrgApacheLuceneSearchMultiTermQuery 1
#define INCLUDE_OrgApacheLuceneSearchMultiTermQuery 1
#include "org/apache/lucene/search/MultiTermQuery.h"

#define RESTRICT_OrgApacheLuceneSearchRegexRegexQueryCapable 1
#define INCLUDE_OrgApacheLuceneSearchRegexRegexQueryCapable 1
#include "org/apache/lucene/search/regex/RegexQueryCapable.h"

@class OrgApacheLuceneIndexIndexReader;
@class OrgApacheLuceneIndexTerm;
@class OrgApacheLuceneSearchFilteredTermEnum;
@protocol OrgApacheLuceneSearchRegexRegexCapabilities;

@interface OrgApacheLuceneSearchRegexRegexQuery : OrgApacheLuceneSearchMultiTermQuery < OrgApacheLuceneSearchRegexRegexQueryCapable >

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneIndexTerm:(OrgApacheLuceneIndexTerm *)term;

- (jboolean)isEqual:(id)o;

- (id<OrgApacheLuceneSearchRegexRegexCapabilities>)getRegexImplementation;

- (OrgApacheLuceneIndexTerm *)getTerm;

- (NSUInteger)hash;

- (void)setRegexImplementationWithOrgApacheLuceneSearchRegexRegexCapabilities:(id<OrgApacheLuceneSearchRegexRegexCapabilities>)impl;

- (NSString *)toStringWithNSString:(NSString *)field;

#pragma mark Protected

- (OrgApacheLuceneSearchFilteredTermEnum *)getEnumWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchRegexRegexQuery)

FOUNDATION_EXPORT void OrgApacheLuceneSearchRegexRegexQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneSearchRegexRegexQuery *self, OrgApacheLuceneIndexTerm *term);

FOUNDATION_EXPORT OrgApacheLuceneSearchRegexRegexQuery *new_OrgApacheLuceneSearchRegexRegexQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchRegexRegexQuery *create_OrgApacheLuceneSearchRegexRegexQuery_initWithOrgApacheLuceneIndexTerm_(OrgApacheLuceneIndexTerm *term);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchRegexRegexQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchRegexRegexQuery")
