//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/Formatter.java
//

#include "J2ObjC_source.h"
#include "org/apache/lucene/search/highlight/Formatter.h"

@interface OrgApacheLuceneSearchHighlightFormatter : NSObject

@end

@implementation OrgApacheLuceneSearchHighlightFormatter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(highlightTermWithNSString:withOrgApacheLuceneSearchHighlightTokenGroup:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "highlightTerm", "LNSString;LOrgApacheLuceneSearchHighlightTokenGroup;" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchHighlightFormatter = { "Formatter", "org.apache.lucene.search.highlight", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchHighlightFormatter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchHighlightFormatter)
