//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/highlight/TextFragment.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/CharSequence.h"
#include "java/lang/Deprecated.h"
#include "java/lang/Math.h"
#include "java/lang/StringBuffer.h"
#include "java/lang/annotation/Annotation.h"
#include "org/apache/lucene/search/highlight/TextFragment.h"

__attribute__((unused)) static IOSObjectArray *OrgApacheLuceneSearchHighlightTextFragment__Annotations$0();

@implementation OrgApacheLuceneSearchHighlightTextFragment

- (instancetype)initWithJavaLangCharSequence:(id<JavaLangCharSequence>)markedUpText
                                     withInt:(jint)textStartPos
                                     withInt:(jint)fragNum {
  OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangCharSequence_withInt_withInt_(self, markedUpText, textStartPos, fragNum);
  return self;
}

- (instancetype)initWithJavaLangStringBuffer:(JavaLangStringBuffer *)markedUpText
                                     withInt:(jint)textStartPos
                                     withInt:(jint)fragNum {
  OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangStringBuffer_withInt_withInt_(self, markedUpText, textStartPos, fragNum);
  return self;
}

- (void)setScoreWithFloat:(jfloat)score {
  self->score_ = score;
}

- (jfloat)getScore {
  return score_;
}

- (void)mergeWithOrgApacheLuceneSearchHighlightTextFragment:(OrgApacheLuceneSearchHighlightTextFragment *)frag2 {
  textEndPos_ = ((OrgApacheLuceneSearchHighlightTextFragment *) nil_chk(frag2))->textEndPos_;
  score_ = JavaLangMath_maxWithFloat_withFloat_(score_, frag2->score_);
}

- (jboolean)followsWithOrgApacheLuceneSearchHighlightTextFragment:(OrgApacheLuceneSearchHighlightTextFragment *)fragment {
  return textStartPos_ == ((OrgApacheLuceneSearchHighlightTextFragment *) nil_chk(fragment))->textEndPos_;
}

- (jint)getFragNum {
  return fragNum_;
}

- (NSString *)description {
  return [((id<JavaLangCharSequence>) nil_chk([((id<JavaLangCharSequence>) nil_chk(markedUpText_)) subSequenceFrom:textStartPos_ to:textEndPos_])) description];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 1, -1, -1, 2, -1 },
    { NULL, "V", 0x0, 3, 4, -1, -1, -1, -1 },
    { NULL, "F", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 7, 6, -1, -1, -1, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 8, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaLangCharSequence:withInt:withInt:);
  methods[1].selector = @selector(initWithJavaLangStringBuffer:withInt:withInt:);
  methods[2].selector = @selector(setScoreWithFloat:);
  methods[3].selector = @selector(getScore);
  methods[4].selector = @selector(mergeWithOrgApacheLuceneSearchHighlightTextFragment:);
  methods[5].selector = @selector(followsWithOrgApacheLuceneSearchHighlightTextFragment:);
  methods[6].selector = @selector(getFragNum);
  methods[7].selector = @selector(description);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "markedUpText_", "LJavaLangCharSequence;", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "fragNum_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "textStartPos_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "textEndPos_", "I", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
    { "score_", "F", .constantValue.asLong = 0, 0x0, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LJavaLangCharSequence;II", "LJavaLangStringBuffer;II", (void *)&OrgApacheLuceneSearchHighlightTextFragment__Annotations$0, "setScore", "F", "merge", "LOrgApacheLuceneSearchHighlightTextFragment;", "follows", "toString" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchHighlightTextFragment = { "TextFragment", "org.apache.lucene.search.highlight", ptrTable, methods, fields, 7, 0x1, 8, 5, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchHighlightTextFragment;
}

@end

void OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangCharSequence_withInt_withInt_(OrgApacheLuceneSearchHighlightTextFragment *self, id<JavaLangCharSequence> markedUpText, jint textStartPos, jint fragNum) {
  NSObject_init(self);
  self->markedUpText_ = markedUpText;
  self->textStartPos_ = textStartPos;
  self->fragNum_ = fragNum;
}

OrgApacheLuceneSearchHighlightTextFragment *new_OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangCharSequence_withInt_withInt_(id<JavaLangCharSequence> markedUpText, jint textStartPos, jint fragNum) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchHighlightTextFragment, initWithJavaLangCharSequence_withInt_withInt_, markedUpText, textStartPos, fragNum)
}

OrgApacheLuceneSearchHighlightTextFragment *create_OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangCharSequence_withInt_withInt_(id<JavaLangCharSequence> markedUpText, jint textStartPos, jint fragNum) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchHighlightTextFragment, initWithJavaLangCharSequence_withInt_withInt_, markedUpText, textStartPos, fragNum)
}

void OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangStringBuffer_withInt_withInt_(OrgApacheLuceneSearchHighlightTextFragment *self, JavaLangStringBuffer *markedUpText, jint textStartPos, jint fragNum) {
  NSObject_init(self);
  self->markedUpText_ = markedUpText;
  self->textStartPos_ = textStartPos;
  self->fragNum_ = fragNum;
}

OrgApacheLuceneSearchHighlightTextFragment *new_OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangStringBuffer_withInt_withInt_(JavaLangStringBuffer *markedUpText, jint textStartPos, jint fragNum) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchHighlightTextFragment, initWithJavaLangStringBuffer_withInt_withInt_, markedUpText, textStartPos, fragNum)
}

OrgApacheLuceneSearchHighlightTextFragment *create_OrgApacheLuceneSearchHighlightTextFragment_initWithJavaLangStringBuffer_withInt_withInt_(JavaLangStringBuffer *markedUpText, jint textStartPos, jint fragNum) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchHighlightTextFragment, initWithJavaLangStringBuffer_withInt_withInt_, markedUpText, textStartPos, fragNum)
}

IOSObjectArray *OrgApacheLuceneSearchHighlightTextFragment__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaLangDeprecated() } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchHighlightTextFragment)
