//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/BoostingQuery.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheLuceneSearchBoostingQuery")
#ifdef RESTRICT_OrgApacheLuceneSearchBoostingQuery
#define INCLUDE_ALL_OrgApacheLuceneSearchBoostingQuery 0
#else
#define INCLUDE_ALL_OrgApacheLuceneSearchBoostingQuery 1
#endif
#undef RESTRICT_OrgApacheLuceneSearchBoostingQuery

#if !defined (OrgApacheLuceneSearchBoostingQuery_) && (INCLUDE_ALL_OrgApacheLuceneSearchBoostingQuery || defined(INCLUDE_OrgApacheLuceneSearchBoostingQuery))
#define OrgApacheLuceneSearchBoostingQuery_

#define RESTRICT_OrgApacheLuceneSearchQuery 1
#define INCLUDE_OrgApacheLuceneSearchQuery 1
#include "org/apache/lucene/search/Query.h"

@class OrgApacheLuceneIndexIndexReader;

@interface OrgApacheLuceneSearchBoostingQuery : OrgApacheLuceneSearchQuery

#pragma mark Public

- (instancetype)initWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)match
                    withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)context
                                         withFloat:(jfloat)boost;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (OrgApacheLuceneSearchQuery *)rewriteWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader;

- (NSString *)toStringWithNSString:(NSString *)field;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchBoostingQuery)

FOUNDATION_EXPORT void OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchBoostingQuery *self, OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost);

FOUNDATION_EXPORT OrgApacheLuceneSearchBoostingQuery *new_OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheLuceneSearchBoostingQuery *create_OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheLuceneSearchBoostingQuery)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheLuceneSearchBoostingQuery")
