//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: jar:file:wdxxl_lucene_350_highlighter.jar!org/apache/lucene/search/BoostingQuery.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/lang/Float.h"
#include "org/apache/lucene/index/IndexReader.h"
#include "org/apache/lucene/search/BooleanClause.h"
#include "org/apache/lucene/search/BooleanQuery.h"
#include "org/apache/lucene/search/BoostingQuery.h"
#include "org/apache/lucene/search/DefaultSimilarity.h"
#include "org/apache/lucene/search/Query.h"
#include "org/apache/lucene/search/Searcher.h"
#include "org/apache/lucene/search/Similarity.h"

@interface OrgApacheLuceneSearchBoostingQuery () {
 @public
  jfloat boost_BoostingQuery_;
  OrgApacheLuceneSearchQuery *match_;
  OrgApacheLuceneSearchQuery *context_;
}

@end

J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchBoostingQuery, match_, OrgApacheLuceneSearchQuery *)
J2OBJC_FIELD_SETTER(OrgApacheLuceneSearchBoostingQuery, context_, OrgApacheLuceneSearchQuery *)

@interface OrgApacheLuceneSearchBoostingQuery_1 : OrgApacheLuceneSearchBooleanQuery {
 @public
  OrgApacheLuceneSearchBoostingQuery *this$0_;
}

- (instancetype)initWithOrgApacheLuceneSearchBoostingQuery:(OrgApacheLuceneSearchBoostingQuery *)outer$;

- (OrgApacheLuceneSearchSimilarity *)getSimilarityWithOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchBoostingQuery_1)

__attribute__((unused)) static void OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery_1 *self, OrgApacheLuceneSearchBoostingQuery *outer$);

__attribute__((unused)) static OrgApacheLuceneSearchBoostingQuery_1 *new_OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneSearchBoostingQuery_1 *create_OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery *outer$);

@interface OrgApacheLuceneSearchBoostingQuery_1_1 : OrgApacheLuceneSearchDefaultSimilarity {
 @public
  OrgApacheLuceneSearchBoostingQuery_1 *this$0_;
}

- (instancetype)initWithOrgApacheLuceneSearchBoostingQuery_1:(OrgApacheLuceneSearchBoostingQuery_1 *)outer$;

- (jfloat)coordWithInt:(jint)overlap
               withInt:(jint)max;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheLuceneSearchBoostingQuery_1_1)

__attribute__((unused)) static void OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1_1 *self, OrgApacheLuceneSearchBoostingQuery_1 *outer$);

__attribute__((unused)) static OrgApacheLuceneSearchBoostingQuery_1_1 *new_OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1 *outer$) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgApacheLuceneSearchBoostingQuery_1_1 *create_OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1 *outer$);

@implementation OrgApacheLuceneSearchBoostingQuery

- (instancetype)initWithOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)match
                    withOrgApacheLuceneSearchQuery:(OrgApacheLuceneSearchQuery *)context
                                         withFloat:(jfloat)boost {
  OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(self, match, context, boost);
  return self;
}

- (OrgApacheLuceneSearchQuery *)rewriteWithOrgApacheLuceneIndexIndexReader:(OrgApacheLuceneIndexIndexReader *)reader {
  OrgApacheLuceneSearchBooleanQuery *result = new_OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(self);
  [result addWithOrgApacheLuceneSearchQuery:match_ withOrgApacheLuceneSearchBooleanClause_Occur:JreLoadEnum(OrgApacheLuceneSearchBooleanClause_Occur, MUST)];
  [result addWithOrgApacheLuceneSearchQuery:context_ withOrgApacheLuceneSearchBooleanClause_Occur:JreLoadEnum(OrgApacheLuceneSearchBooleanClause_Occur, SHOULD)];
  return result;
}

- (NSUInteger)hash {
  jint prime = 31;
  jint result = 1;
  result = prime * result + JavaLangFloat_floatToIntBitsWithFloat_(boost_BoostingQuery_);
  result = prime * result + ((context_ == nil) ? 0 : ((jint) [((OrgApacheLuceneSearchQuery *) nil_chk(context_)) hash]));
  result = prime * result + ((match_ == nil) ? 0 : ((jint) [((OrgApacheLuceneSearchQuery *) nil_chk(match_)) hash]));
  return result;
}

- (jboolean)isEqual:(id)obj {
  if (self == obj) return true;
  if (obj == nil) return false;
  if ([self java_getClass] != [obj java_getClass]) return false;
  OrgApacheLuceneSearchBoostingQuery *other = (OrgApacheLuceneSearchBoostingQuery *) cast_chk(obj, [OrgApacheLuceneSearchBoostingQuery class]);
  if (JavaLangFloat_floatToIntBitsWithFloat_(boost_BoostingQuery_) != JavaLangFloat_floatToIntBitsWithFloat_(other->boost_BoostingQuery_)) return false;
  if (context_ == nil) {
    if (other->context_ != nil) return false;
  }
  else if (![context_ isEqual:other->context_]) return false;
  if (match_ == nil) {
    if (other->match_ != nil) return false;
  }
  else if (![match_ isEqual:other->match_]) return false;
  return true;
}

- (NSString *)toStringWithNSString:(NSString *)field {
  return JreStrcat("$C$", [((OrgApacheLuceneSearchQuery *) nil_chk(match_)) toStringWithNSString:field], '/', [((OrgApacheLuceneSearchQuery *) nil_chk(context_)) toStringWithNSString:field]);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchQuery;", 0x1, 1, 2, 3, -1, -1, -1 },
    { NULL, "I", 0x1, 4, -1, -1, -1, -1, -1 },
    { NULL, "Z", 0x1, 5, 6, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 7, 8, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchQuery:withOrgApacheLuceneSearchQuery:withFloat:);
  methods[1].selector = @selector(rewriteWithOrgApacheLuceneIndexIndexReader:);
  methods[2].selector = @selector(hash);
  methods[3].selector = @selector(isEqual:);
  methods[4].selector = @selector(toStringWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "boost_BoostingQuery_", "F", .constantValue.asLong = 0, 0x2, 9, -1, -1, -1 },
    { "match_", "LOrgApacheLuceneSearchQuery;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
    { "context_", "LOrgApacheLuceneSearchQuery;", .constantValue.asLong = 0, 0x2, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LOrgApacheLuceneSearchQuery;LOrgApacheLuceneSearchQuery;F", "rewrite", "LOrgApacheLuceneIndexIndexReader;", "LJavaIoIOException;", "hashCode", "equals", "LNSObject;", "toString", "LNSString;", "boost" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchBoostingQuery = { "BoostingQuery", "org.apache.lucene.search", ptrTable, methods, fields, 7, 0x1, 5, 3, -1, -1, -1, -1, -1 };
  return &_OrgApacheLuceneSearchBoostingQuery;
}

@end

void OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchBoostingQuery *self, OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost) {
  OrgApacheLuceneSearchQuery_init(self);
  self->match_ = match;
  self->context_ = (OrgApacheLuceneSearchQuery *) cast_chk([((OrgApacheLuceneSearchQuery *) nil_chk(context)) java_clone], [OrgApacheLuceneSearchQuery class]);
  self->boost_BoostingQuery_ = boost;
  [((OrgApacheLuceneSearchQuery *) nil_chk(self->context_)) setBoostWithFloat:0.0f];
}

OrgApacheLuceneSearchBoostingQuery *new_OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchBoostingQuery, initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_, match, context, boost)
}

OrgApacheLuceneSearchBoostingQuery *create_OrgApacheLuceneSearchBoostingQuery_initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_(OrgApacheLuceneSearchQuery *match, OrgApacheLuceneSearchQuery *context, jfloat boost) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchBoostingQuery, initWithOrgApacheLuceneSearchQuery_withOrgApacheLuceneSearchQuery_withFloat_, match, context, boost)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgApacheLuceneSearchBoostingQuery)

@implementation OrgApacheLuceneSearchBoostingQuery_1

- (instancetype)initWithOrgApacheLuceneSearchBoostingQuery:(OrgApacheLuceneSearchBoostingQuery *)outer$ {
  OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(self, outer$);
  return self;
}

- (OrgApacheLuceneSearchSimilarity *)getSimilarityWithOrgApacheLuceneSearchSearcher:(OrgApacheLuceneSearchSearcher *)searcher {
  return new_OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(self);
}

- (NSUInteger)countByEnumeratingWithState:(NSFastEnumerationState *)state objects:(__unsafe_unretained id *)stackbuf count:(NSUInteger)len {
  return JreDefaultFastEnumeration(self, state, stackbuf, len);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgApacheLuceneSearchSimilarity;", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchBoostingQuery:);
  methods[1].selector = @selector(getSimilarityWithOrgApacheLuceneSearchSearcher:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneSearchBoostingQuery;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "getSimilarity", "LOrgApacheLuceneSearchSearcher;", "LOrgApacheLuceneSearchBoostingQuery;", "rewriteWithOrgApacheLuceneIndexIndexReader:" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchBoostingQuery_1 = { "", "org.apache.lucene.search", ptrTable, methods, fields, 7, 0x8018, 2, 1, 2, -1, 3, -1, -1 };
  return &_OrgApacheLuceneSearchBoostingQuery_1;
}

@end

void OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery_1 *self, OrgApacheLuceneSearchBoostingQuery *outer$) {
  self->this$0_ = outer$;
  OrgApacheLuceneSearchBooleanQuery_init(self);
}

OrgApacheLuceneSearchBoostingQuery_1 *new_OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery *outer$) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchBoostingQuery_1, initWithOrgApacheLuceneSearchBoostingQuery_, outer$)
}

OrgApacheLuceneSearchBoostingQuery_1 *create_OrgApacheLuceneSearchBoostingQuery_1_initWithOrgApacheLuceneSearchBoostingQuery_(OrgApacheLuceneSearchBoostingQuery *outer$) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchBoostingQuery_1, initWithOrgApacheLuceneSearchBoostingQuery_, outer$)
}

@implementation OrgApacheLuceneSearchBoostingQuery_1_1

- (instancetype)initWithOrgApacheLuceneSearchBoostingQuery_1:(OrgApacheLuceneSearchBoostingQuery_1 *)outer$ {
  OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(self, outer$);
  return self;
}

- (jfloat)coordWithInt:(jint)overlap
               withInt:(jint)max {
  switch (overlap) {
    case 1:
    return 1.0f;
    case 2:
    return this$0_->this$0_->boost_BoostingQuery_;
    default:
    return 0.0f;
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "F", 0x1, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgApacheLuceneSearchBoostingQuery_1:);
  methods[1].selector = @selector(coordWithInt:withInt:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LOrgApacheLuceneSearchBoostingQuery_1;", .constantValue.asLong = 0, 0x1012, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "coord", "II", "LOrgApacheLuceneSearchBoostingQuery_1;", "getSimilarityWithOrgApacheLuceneSearchSearcher:" };
  static const J2ObjcClassInfo _OrgApacheLuceneSearchBoostingQuery_1_1 = { "", "org.apache.lucene.search", ptrTable, methods, fields, 7, 0x8018, 2, 1, 2, -1, 3, -1, -1 };
  return &_OrgApacheLuceneSearchBoostingQuery_1_1;
}

@end

void OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1_1 *self, OrgApacheLuceneSearchBoostingQuery_1 *outer$) {
  self->this$0_ = outer$;
  OrgApacheLuceneSearchDefaultSimilarity_init(self);
}

OrgApacheLuceneSearchBoostingQuery_1_1 *new_OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1 *outer$) {
  J2OBJC_NEW_IMPL(OrgApacheLuceneSearchBoostingQuery_1_1, initWithOrgApacheLuceneSearchBoostingQuery_1_, outer$)
}

OrgApacheLuceneSearchBoostingQuery_1_1 *create_OrgApacheLuceneSearchBoostingQuery_1_1_initWithOrgApacheLuceneSearchBoostingQuery_1_(OrgApacheLuceneSearchBoostingQuery_1 *outer$) {
  J2OBJC_CREATE_IMPL(OrgApacheLuceneSearchBoostingQuery_1_1, initWithOrgApacheLuceneSearchBoostingQuery_1_, outer$)
}
